# Generated by Django 5.0 on 2023-12-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
