# Generated by Django 5.0 on 2023-12-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApi', '0002_alter_logintable_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollno', models.IntegerField(max_length=50)),
                ('branch', models.CharField(max_length=60)),
            ],
        ),
    ]
