# Generated by Django 5.0 on 2023-12-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApi', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='himanshu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
